version: "3"

vars:
  PROGRAM: gochro

tasks:
  update:
    cmds:
      - go get -u
      - go mod tidy -v

  build:
    aliases: [default]
    cmds:
      - go fmt ./...
      - go vet ./...
      - go build -o {{.PROGRAM}}

  test:
    env:
      CGO_ENABLED: 1 # required by -race
    cmds:
      - go test -race -cover ./...

  run:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -debug

  docker:
    cmds:
      - docker build -t {{.PROGRAM}} .
      - docker run --rm -it -p 8080:8080 {{.PROGRAM}} -host 0.0.0.0:8080 -debug -disable-sandbox

  lint:
    cmds:
      - golangci-lint run ./... --timeout=30m
      - go mod tidy

  lint-update:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b {{ .GOPATH }}/bin
      - golangci-lint --version
    vars:
      GOPATH:
        sh: go env GOPATH
